### ISSUE TITLE
Why is IXform::getInheritsXforms() not const?

### ISSUE THREAD

**Issue by sybrenstuvel** [alembic/alembic#110] opened 2017-02-14 16:53 UTC
Hey Alembic team,

[IXform::getInheritsXforms()](https://github.com/alembic/alembic/blob/9ec30e97e9f470c4d14a2dd57e911d9dfae1880f/lib/Alembic/AbcGeom/IXform.h#L136) is documented as a shortcut for `XformSample::getInheritsXforms() const` so that one doesn't have to create a sample object. However, `XformSample::getInheritsXforms()` is `const`, while `IXform::getInheritsXforms()` is not.

To me it seems that the [implementation of IXform::getInheritsXforms()](https://github.com/alembic/alembic/blob/9ec30e97e9f470c4d14a2dd57e911d9dfae1880f/lib/Alembic/AbcGeom/IXform.cpp#L319) doesn't change the `IXform`, and my compiler (GCC 5.4.0) also doesn't complain if I declare the function `const`.

**Comment by lamiller0** [comment] 2017-02-14 17:49
Yes, it's a way to read from the inherits property without reading the rest of the xform.

I suspect that in a previous version of Alembic the function wasn't const safe, but after a quick perusal, it looks like it now is. (as GCC 5.4.0 confirmed for you)

**Comment by lamiller0** [comment] 2017-03-25 04:39
Released in 1.7.1

**Closed by lamiller0** 2017-03-25 04:39 UTC
